name: Java CI/CD with Docker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Define que todos os passos deste job rodam dentro da pasta da API
    defaults:
      run:
        working-directory: ./delivery-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean package -Dmaven.gitcommitid.skip=true

      - name: Generate JaCoCo Report
        run: mvn jacoco:report

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./delivery-api

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        # O ponto (.) no final indica o contexto do build dentro de delivery-api
        run: docker build -t delivery-api:${{ github.sha }} .

  deploy-homolog:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Ajustado para sua branch atual
    steps:
      - name: Deploy to Staging
        run: |
          echo "Realizando deploy automático em ambiente de homologação..."
